

export function standalonePhrases() {
	return [
		"Launch Attack!",
		"Begin Assault!",
		"Roll To Hit!",
		"Roll Attack!",
		"Hope For 20s!",
		"Send Out The Swarm!",
		"Unleash The Mob!",
		"Cause A Ruckus!",
		"Run Them Down!",
		"Begin The Blitz!",
		"Farm Some XP!",
		"Off With Their Heads!",
		"Collect Their Gold!",
		"To Battle!",
		"Vanquish The Evil!",
		"Banish The Shadows!",
		
		
	]
}

export function badGuyNames() {
	return [
		"nogoodnik",
		"loser",
		"miscreant",
		"no-good",
		"scoundrel",
		"reprobate",
		"evildoer",
		"criminal",
		"rascal",
		"rogue",
		"baddy",
		"villain",
		"wrongdoer",
		"crook",
		"knave",
		"lawbreaker",
		"bad egg",
		"offender",
		"malefactor",
		"malfeasant",
		"sinner",
		"misfeasor",
		"baddie",
		"meanie",
		"meany",
		"monster",
		"delinquent",
		"felon",
		"transgressor",
		"scumbag",
		"outlaw",
		"wretch",
		"convict",
		"lowlife",
		"creep",
		"dog",
		"con",
		"dastard",
		"crim",
		"rat",
		"snake",
		"swine",
		"scamp",
		"lout",
		"infractor",
		"heavy",
		"stinker",
		"good-for-nothing",
		"bad character",
		"unprincipled person",
		"culprit",
		"jerk",
		"cretin",
		"dirtbag",
		"degenerate",
		"savage",
		"sleazebag",
		"thug",
		"brute",
		"slimeball",
		"hound",
		"devil",
		"fiend",
		"slime",
		"tyrant",
		"stinkard",
		"perpetrator",
		"perp",
		"beast",
		"guilty party",
		"hooligan",
		"shyster",
		"ruffian",
		"antagonist",
		"caitiff",
		"scum",
		"varmint",
		"psychopath",
		"rapscallion",
		"varlet",
		"scallywag",
		"vermin",
		"sleaze",
		"scapegrace",
		"sociopath",
		"scalawag",
		"shark",
		"sleazeball",
		"blackhat",
		"scuzzball",
		"nasty person",
		"mischief maker",
		"evil person",
		"despicable person",
		"trespasser",
		"swindler",
		"bandit",
		"gangster",
		"thief",
		"racketeer",
		"robber",
		"mugger",
		"fraudster",
		"profligate",
		"fraud",
		"trickster",
		"terrorist",
		"charlatan",
		"incorrigible",
		"bully",
		"hoodlum",
		"immoralist",
		"blackguard",
		"person responsible",
		"maggot",
		"buzzard",
		"worm",
		"violator",
		"demon",		
	];
}


export function actionWords() {
	return [
		"strike",
		"attack",
		"assault",
		"assail",
		"invade",
		"charge",
		"pounce",
		"rush",
		"smite",
		"storm",
		"trash",
		"aggress",
		"beset",
		"raid",
		"sic",
		"sick",
		"afflict",
		"bushwhack",
		"devastate",
		"hit",
		"descend on",
		"pounce on",
		"fall on",
		"jump on",
		"set on",
		"lay waste to",
		"turn on",
		"deal a blow to",
		"go in on",
		"besiege",
		"blindside",
		"smash",
		"advance on",
		"openfire on",
		"tear into",
		"launch an attack on",
		"launch an assault on",
		"launch a raid on",
		"attempt to capture",
		"onslaught",
		"take by storm",
		"strike at",
		"swoop on",
		"fly at",
		"blitz",
		"ambush",
		"light into",
		"jump",
		"goat",
		"pitch into",
		"let fly at",
		"round on",
		"capture",
		"mug",
		"marchin to",
		"overwhelm",
		"infiltrate",
		"bombard",
		"penetrate",
		"have at",
		"lash out at",
		"seize",
		"beatup",
		"beatup on",
		"set at",
		"sally",
		"fire on",
		"takedown",
		"surge over",
		"dive",
		"spring",
		"bust",
		"bound",
		"spring on",
		"lungeat",
		"surge",
		"dash",
		"go for",
		"hit out at",
		"lace into",
		"run at",
		"work over",
		"come at",
		"have a go at",
		"overrun",
		"hurt",
		"batter",
		"harm",
		"overcome",
		"blast",
		"accost",
		"charge at",
		"fight",
		"quarrel",
		"harry",
		"maltreat",
		"take",
		"cook",
		"blister",
		"shootdown",
		"torpedo",
		"bomb",
		"weigh into",
		"sail into",
		"set inon",
		"makea foray on",
		"make a sortie on",
		"surge into",
		"conduct an offensive on",
		"take on",
		"surprise",
		"march on",
		"foray into",
		"sally forth",
		"swoopdown upon",
		"turn to violence on",
		"lay siege to",
		"hold up",
		"lurch at",
		"drive at",
		"burst",
		"swing",
		"make for",
		"secure",
		"conquer",
		"launch at",
		"give a beating to",
		"spring at",
		"go after",
		"rushup on",
		"duff up",
		"beat the living daylights out of",
		"rush at",
		"rough up",
		"breach",
		"pillage",
		"advance",
		"plunder",
		"maraud",
		"ravage",
		"combat",
		"strafe",
		"swoop",
		"leap on",
		"encroach",
		"shell",
		"fire at",
		"begin hostilities towards",
		"dive at",
		"dart",
		"grab",
		"tackle",
		"drop",
		"snatch",
		"bound at",
		"begin an assault on",
		"take the offensive to",
		"swoop down on",
		"attack suddenly at",
		"drop down on",
	];
}
