
function actionWords() {
  return [
    strike,
    attack,
    assault,
    assail,
    invade,
    charge,
    descend,
    pounce,
    rush,
    smite,
    storm,
    trash,
    aggress,
    beset,
    raid,
    sic,
    sick,
    afflict,
    bushwhack,
    devastate,
    hit,
    descend on,
    descend upon,
    pounce on,
    pounce upon,
    set upon,
    fall on,
    jump on,
    make an assault on,
    make an attack on,
    set on,
    fall upon,
    lay into,
    turn on,
    deal a blow to,
    go in on,
    besiege,
    blindside,
    smash,
    advance on,
    launch oneself at,
    open fire on,
    tear into,
    launch an attack on,
    make an assault on,
    make a raid on,
    attempt to capture,
    make an onslaught on,
    take by storm,
    strike at,
    swoop on,
    fly at,
    blitz,
    ambush,
    light into,
    jump,
    go at,
    pitch into,
    let fly at,
    round on,
    capture,
    mug,
    march into,
    overwhelm,
    infiltrate,
    bombard,
    penetrate,
    have at,
    lash out at,
    seize,
    beat up,
    beat up on,
    set at,
    sally,
    fire on,
    take down,
    surge over,
    leap,
    dive,
    spring,
    bust,
    bound,
    spring on,
    lunge at,
    surge,
    dash,
    go for,
    hit out at,
    lace into,
    run at,
    work over,
    come at,
    have a go at,
    overrun,
    hurt,
    batter,
    harm,
    overcome,
    blast,
    accost,
    charge at,
    fight,
    quarrel,
    harry,
    maltreat,
    take,
    cook,
    blister,
    shoot down,
    torpedo,
    bomb,
    weigh into,
    sail into,
    set in on,
    make a foray on,
    make a sortie on,
    surge into,
    conduct an offensive on,
    take on,
    surprise,
    march on,
    foray into,
    sally forth,
    make inroads on,
    swoop down upon,
    turn to violence on,
    lay siege to,
    thrust,
    lie in wait for,
    hold up,
    lurch,
    drive,
    burst,
    swing,
    move suddenly onto,
    make for,
    secure,
    conquer,
    launch at,
    give a beating to,
    spring at,
    go after,
    rush upon,
    duff up,
    beat the living daylights out of,
    rush at,
    rough up,
    breach,
    pillage,
    advance,
    plunder,
    maraud,
    ravage,
    combat,
    strafe,
    swoop,
    leap on,
    encroach,
    shell,
    fire at,
    begin hostilities towards,
    dive at,
    dart,
    grab,
    tackle,
    drop,
    snatch,
    bound at,
    begin an assault on,
    take the offensive to,
    swoop down on,
    attack suddenly at,
    drop down on,
  ]
}
